repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 75ca4ad908dc4a99f57921f29b7e6c1521e10b26
    hooks:
      - id: clang-format
        args: [--style=file]
        files: '\\.(c|h|)$'
