name: Build

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build app
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 #v6.0.2
        with:
          path: seven-clicker-sample
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
        with:
          python-version: 3.12

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@360ff9b36e58499d9eb28015cdcde7ca03a5b04d #v1.0.12
        with:
          app-path: seven-clicker-sample
          toolchains: arm-zephyr-eabi
          ccache-cache-key: ubuntu-22.04

      - name: Build firmware
        working-directory: seven-clicker-sample
        shell: bash
        run: west build -p always -b mikroe_clicker_2 app
